### ISSUE TITLE
Ready for Grading Week 2 Assignment

### ISSUE THREAD

**Issue by dmargie-matc** [madisoncollege-it-programs/python-scripting-dmargie#1]

**Comment by cethenmc** [comment]
Hi, Derek.  I do not see anything in your repository on GitHub.  Please push to the repository.  ~Chris

**Comment by cethenmc** [comment]
Hi, Derek.  Week 2, Assignment #1, complete and good!

**Comment by dmargie-matc** [comment]
Thank you! I’ll see if I can fix my error with Github.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
