### ISSUE TITLE
First script for Python assignment complete

### ISSUE THREAD

**Issue by dmargie-matc** [madisoncollege-it-programs/python-scripting-dmargie#2]
One thing I wasn't completely clear on is whether or not adding a variable within a script has the same function as doing it through python3.

**Comment by cethenmc** [comment]
Hi, Derek.  I do not see anything in your repository on GitHub.  Please push to the repository.  ~Chris

**Comment by dmargie-matc** [comment]
Hello,

That’s strange, because I can see it when I go to the repository on Netlab. Maybe I submitted it to the wrong one? Here’s a screenshot:
***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cethenmc** [comment]
Nice...adding in the input and formatted strings.  ~Chris
