### ISSUE TITLE
Here is Derek Gerber-Margie's Week 3 scripting assignment

### ISSUE THREAD

**Issue by dmargie-matc** [madisoncollege-it-programs/python-scripting-dmargie#3]

**Comment by cethenmc** [comment]
Derek - You need to rework this and hand in again.

Starting no later than #5 you should start using the formatted strings with the colon, filler, alignment, etc.  You should also not repeat blue 10 times in your code.

Your challenge is to make these lines of code the shortest you can, using what that lesson taught, and rendering the same result.

Additionally, please download the Word document and be sure to count the spaces in the strings, so you know where to put them, or how long to make the formatted string.  And reverse the appropriate colors using slicing in #13.

Please book me if you feel you need assistance.  Thanks.

Chris

**Comment by cethenmc** [comment]
Derek - You are welcome to resubmit this, as I recommended 12 days ago.  However, at this point, I am recording as 3.5 out of 8, so there is a grade in the grade book, but you still need to redo as formatted strings using the colon syntax.  Please see my previous message.  ~Chris
